### ISSUE TITLE
Match error when loading aggregate with id '*'

### ISSUE THREAD

**Issue by javaguruen** [NextGenTel/akka-tools#18]
If you try to load an aggregate with name '\*', all events of that aggregate type is loaded (* being treated as wildcard in select). Thees events are wrapped in JournalEntry which gives a match error in GeneralAggregateBase.scala:128. This could/should be checked for in EnhancedPersistenceActor:161 before casting event to E.

Happends in akka-tools version 1.0.12

**Comment by mbknor** [comment]
Do you have a stacktrace?

**Comment by javaguruen** [comment]
```scala
scala.MatchError: JournalEntry(PersistenceId{typePath='/shipping-order/', id='DETAILS_REMOVED'},OnUpdateState(NewShippingOrderRequest(DETAILS_REMOVED)) (of class no.nextgentel.oss.akkatools.persistence.jdbcjournal.JournalEntry)
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:253) ~[scala-library-2.11.7.jar:na]
	at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:251) ~[scala-library-2.11.7.jar:na]
	at no.nextgentel.oss.akkatools.aggregate.GeneralAggregateBase$$anonfun$onEvent$1.applyOrElse(GeneralAggregateBase.scala:128) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at no.nextgentel.oss.akkatools.persistence.EnhancedPersistentActor.onEventInternal(EnhancedPersistentActor.scala:261) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at no.nextgentel.oss.akkatools.persistence.EnhancedPersistentActor.onReceiveRecover(EnhancedPersistentActor.scala:210) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at no.nextgentel.oss.akkatools.persistence.EnhancedPersistentActor$$anonfun$receiveRecover$1.applyOrElse(EnhancedPersistentActor.scala:162) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at akka.persistence.Eventsourced$$anon$3$$anonfun$1.applyOrElse(Eventsourced.scala:481) ~[akka-persistence_2.11-2.4.8.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484) ~[akka-actor_2.11-2.4.8.jar:na]
	at no.nextgentel.oss.akkatools.persistence.EnhancedPersistentActor.akka$persistence$Eventsourced$$super$aroundReceive(EnhancedPersistentActor.scala:35) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:545) ~[akka-persistence_2.11-2.4.8.jar:na]
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:182) ~[akka-persistence_2.11-2.4.8.jar:na]
	at no.nextgentel.oss.akkatools.persistence.EnhancedPersistentActor.akka$persistence$AtLeastOnceDeliveryLike$$super$aroundReceive(EnhancedPersistentActor.scala:35) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at akka.persistence.AtLeastOnceDeliveryLike$class.aroundReceive(AtLeastOnceDelivery.scala:357) ~[akka-persistence_2.11-2.4.8.jar:na]
	at no.nextgentel.oss.akkatools.persistence.EnhancedPersistentActor.akka$actor$DiagnosticActorLogging$$super$aroundReceive(EnhancedPersistentActor.scala:35) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at akka.actor.DiagnosticActorLogging$class.aroundReceive(Actor.scala:329) ~[akka-actor_2.11-2.4.8.jar:na]
	at no.nextgentel.oss.akkatools.persistence.EnhancedPersistentActor.aroundReceive(EnhancedPersistentActor.scala:35) ~[akka-tools-persistence_2.11-1.0.12-b1-SNAPSHOT.jar:1.0.12-b1-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526) [akka-actor_2.11-2.4.8.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:495) [akka-actor_2.11-2.4.8.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.4.8.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.4.8.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.4.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
```
